Repository Gosrock/Ticket-Backend-22nd, pull requests merged in 2022-08, with the labels that each got.

#102 🚀 : feat(queue): 주문 상태 변경 시, 슬랙 알림 기능 추가 및 메시지 포맷 변경
  src/orders/orders.service.ts
  src/queue/queue.consumer.sms.ts
  src/queue/queue.consumer.ts
  src/queue/queue.service.ts
Labels: For: Utils, Type: Feature, Type: Refactor

#105 [v0.1.4] sms 포맷, 주문상태변경 알림추가 , 주문 페이지네이션 버그수정
  src/auth/auth.service.ts
  src/auth/dtos/AdminLogin.response.dto.ts
  src/database/repositories/order.repository.ts
  src/orders/dtos/order-find.dto.ts
  src/orders/orders.service.ts
  src/queue/queue.consumer.sms.ts
  src/queue/queue.consumer.ts
  src/queue/queue.service.ts
  src/slack/slackFake.service.ts
  src/users/users.controller.ts
Labels: For: Deploy, Type: Feature, Type: Refactor, For: API

#114 :rocket: feat(queue): 티켓 상태 변경 따로 빼서 작업
  src/auth/auth.service.ts
  src/queue/queue.consumer.ts
  src/queue/queue.service.ts
  src/tickets/tickets.service.ts
Labels: For: Utils, Type: Feature

#115 :hammer: fix(ticket): 티켓 에러, 로직 배포용으로 변경 #111
  src/common/dtos/page/page-options.dto.ts
  src/common/dtos/paging.dto.ts
  src/database/repositories/ticket.repository.ts
  src/tickets/dtos/ticket-on-socket.dto.ts
  src/tickets/tickets.controller.ts
  src/tickets/tickets.service.ts
Labels: For: Deploy, Type: Refactor, Type: Errors/Bugs

#116 [v1.0.0] 프로덕션용 배포
  src/auth/auth.service.ts
  src/common/dtos/page/page-options.dto.ts
  src/common/dtos/paging.dto.ts
  src/database/repositories/order.repository.ts
  src/database/repositories/ticket.repository.ts
  src/database/repositories/user.repository.ts
  src/orders/dtos/order-find.dto.ts
  src/orders/dtos/report.dto.ts
  src/orders/orders.service.ts
  src/queue/queue.consumer.ts
  src/queue/queue.service.ts
  src/tickets/dtos/ticket-on-socket.dto.ts
  src/tickets/tickets.controller.ts
  src/tickets/tickets.service.ts
  src/users/dtos/Comment.response.dto.ts
  src/users/dtos/UserFind.dto.ts
  src/users/dtos/UserTicketNum.response.dto.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: For: Deploy, For: Utils, Type: Feature, Type: Refactor, For: API, Type: Docs/Chore

#119 :hammer: refactor(ticket): 티켓 입장 응답 예시 추가 #118
  src/tickets/tickets.controller.ts
  src/tickets/tickets.service.ts
Labels: Type: Refactor, For: API

#120 [v1.0.1] 티켓모듈 엔터관련 예시에러응답값 추가, 인증번호 exclude
  src/auth/dtos/AdminSendValidationNumber.response.dto.ts
  src/auth/dtos/RequestValidation.response.dto.ts
  src/tickets/tickets.controller.ts
  src/tickets/tickets.service.ts
Labels: For: Deploy, Type: Refactor, For: API

#122 [v1.0.3] user eager option false로 ... 쿼리 속도저하 개선
  src/auth/auth.interface.ts
  src/auth/auth.service.ts
  src/auth/guards/AccessToken.guard.ts
  src/common/decorators/user.decorator.ts
  src/database/entities/user.entity.ts
  src/database/repositories/user.repository.ts
  src/tickets/tickets.controller.ts
  src/tickets/tickets.service.ts
  src/users/users.service.ts
Labels: For: Deploy, For: Utils, Type: Refactor, For: API

#124 응원 댓글 개수 조회 api 구현
  src/database/repositories/comment.repository.ts
  src/users/dtos/Comment.response.dto.ts
  src/users/dtos/CommentNum.response.dto.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: Type: Feature, For: API

#125 [v1.0.4] 응원 댓글 개수 조회 api 구현
  src/database/repositories/comment.repository.ts
  src/users/dtos/Comment.response.dto.ts
  src/users/dtos/CommentNum.response.dto.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: For: Deploy, Type: Feature

#128 [v1.0.5] 티켓 단건조회 수정, 주문모듈 응답값 개선
  src/database/repositories/order.repository.ts
  src/orders/orders.controller.ts
  src/orders/orders.service.ts
  src/tickets/tickets.controller.ts
  src/tickets/tickets.service.ts
Labels: Type: Refactor, For: API

#129 feat(user) : 랜덤 댓글 뽑기 기능(유저 정보 포함)
  src/database/repositories/comment.repository.ts
  src/users/dtos/RandomCommentUser.response.dto.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: Type: Refactor, For: API

#130 [v1.0.6] 랜덤 댓글 뽑기 기능(유저 정보 포함)
  src/database/repositories/comment.repository.ts
  src/users/dtos/RandomCommentUser.response.dto.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: For: Deploy, Type: Feature, For: API

#131 [v1.0.7] 프로덕션 대비 ,인증번호 응답값, 로그 주석처리
  src/auth/auth.controller.ts
  src/auth/dtos/AdminSendValidationNumber.response.dto.ts
  src/auth/dtos/RequestValidation.response.dto.ts
  src/common/utils/makeInstanceByApiProperty.ts
  src/database/repositories/comment.repository.ts
  src/orders/orders.controller.ts
  src/users/users.controller.ts
Labels: For: Deploy, Type: Refactor, For: API

#132 [v1.0.8] 폰인증번호 expose , 어세스토큰 관련 로직수정
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/dtos/Login.response.dto.ts
  src/auth/dtos/RequestValidation.response.dto.ts
  src/auth/guards/AccessToken.guard.ts
  src/common/decorators/SuccessResponse.decorator.ts
  src/database/repositories/user.repository.ts
  src/orders/orders.controller.ts
Labels: For: Deploy, Type: Refactor

#135 [v1.1.0] 프로덕션 대비
  README.md
  src/auth/dtos/RequestValidation.response.dto.ts
Labels: For: Deploy, Type: Refactor, For: API

#136 [v1.1.1] 인증토큰 만료시간변화
  README.md
  src/auth/auth.service.ts
Labels: For: Deploy, Type: Refactor, For: API
