Repository Gosrock/Ticket-Backend-22nd, pull requests merged in 2022-07, with the labels that each got.

#31 Feature/ticket
  .env.local
  package-lock.json
  package.json
  src/auth/auth.service.ts
  src/common/consts/enum.ts
  src/common/dtos/create-ticket.dto.ts
  src/common/dtos/page/page-meta-dto.interface.ts
  src/common/dtos/page/page-meta.dto.ts
  src/common/dtos/page/page-options.dto.ts
  src/common/dtos/page/page.dto.ts
  src/common/dtos/ticket-find.dto.ts
  src/common/dtos/update-ticket-status.dto.ts
  src/common/dtos/user-profile.dto.ts
  src/common/pipes/performance-date-validation.pipe.ts
  src/common/pipes/ticket-status-validation.pipe.ts
  src/common/pipes/ticket-uuid-validation.pipe.ts
  src/database/entities/order.entity.ts
  src/database/entities/ticket.entity.ts
  src/database/repositories/ticket.repository.ts
  src/database/repositories/user.repository.ts
  src/tickets/dtos/create-ticket.dto.ts
  src/tickets/tickets.controller.ts
  src/tickets/tickets.module.ts
  src/tickets/tickets.service.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: 기능 추가

#44 슬랙 알림 모듈 관련해서 인자를 dto로 리팩토링
  src/auth/auth.service.ts
  src/slack/dtos/SlackNewOrder.dto.ts
  src/slack/dtos/SlackOrderStateChange.dto.ts
  src/slack/dtos/SlackTicketQREnterEvent.dto.ts
  src/slack/dtos/SlackTicketStateChange.dto.ts
  src/slack/dtos/SlackValidationNumberDM.dto.ts
  src/slack/dtos/index.ts
  src/slack/slack.service.spec.ts
  src/slack/slack.service.ts
  src/slack/slackFake.service.ts
Labels: For: Utils, Type: Test, Type: Refactor

#46 :hammer: fix(entity) : 유저 프로파일 디티오를 이용한 직렬화과정시 제공 정보 단순화
  src/common/decorators/ApiPaginatedDto.decorator.ts
  src/common/dtos/user-profile.dto.ts
  src/database/entities/order.entity.ts
  src/database/entities/ticket.entity.ts
  src/tickets/tickets.controller.ts
  src/tickets/tickets.service.ts
Labels: For: Utils, Type: Refactor, Type: Docs/Chore

#47 🚀 feat(socket) : 소켓 모듈 구현
  package-lock.json
  package.json
  src/app.module.ts
  src/database/repositories/ticket.repository.ts
  src/socket/socket-admin.gateway.ts
  src/socket/socket-user.gateway.ts
  src/socket/socket.guard.ts
  src/socket/socket.module.ts
  src/socket/socket.service.ts
  src/tickets/dtos/create-ticket.dto.ts
  src/tickets/dtos/ticket-entry-date-validation.dto copy.ts
  src/tickets/dtos/ticket-entry-response.dto.ts
  src/tickets/dtos/ticket-find.dto.ts
  src/tickets/dtos/ticket-on-socket.dto.ts
  src/tickets/dtos/update-ticket-status.dto.ts
  src/tickets/tickets.controller.ts
  src/tickets/tickets.module.ts
  src/tickets/tickets.service.ts
Labels: Type: Feature, For: API

#48 티켓, 채팅모듈 배포
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.module.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/common/decorators/ApiPaginatedDto.decorator.ts
  src/common/dtos/user-profile.dto.ts
  src/config/customConfig.module.ts
  src/database/entities/order.entity.ts
  src/database/entities/ticket.entity.ts
  src/database/repositories/ticket.repository.ts
  src/redis/redis.module.ts
  src/slack/dtos/SlackNewOrder.dto.ts
  src/slack/dtos/SlackOrderStateChange.dto.ts
  src/slack/dtos/SlackTicketQREnterEvent.dto.ts
  src/slack/dtos/SlackTicketStateChange.dto.ts
  src/slack/dtos/SlackValidationNumberDM.dto.ts
  src/slack/dtos/index.ts
  src/slack/slack.service.spec.ts
  src/slack/slack.service.ts
  src/slack/slackFake.service.ts
  src/sms/sms.service.spec.ts
  src/socket/socket-admin.gateway.ts
  src/socket/socket-user.gateway.ts
  src/socket/socket.guard.ts
  src/socket/socket.module.ts
  src/socket/socket.service.ts
  src/tickets/dtos/create-ticket.dto.ts
  src/tickets/dtos/ticket-entry-date-validation.dto copy.ts
  src/tickets/dtos/ticket-entry-response.dto.ts
  src/tickets/dtos/ticket-find.dto.ts
  src/tickets/dtos/ticket-on-socket.dto.ts
  src/tickets/dtos/update-ticket-status.dto.ts
  src/tickets/tickets.controller.ts
  src/tickets/tickets.module.ts
  src/tickets/tickets.service.ts
  src/users/users.module.ts
Labels: For: Deploy, Type: Feature, Type: Refactor, Type: Docs/Chore

#50 :hammer: fix(slack) : 슬랙 fake 서비스에 로거 추가 (#49)
  src/slack/slackFake.service.ts
Labels: For: Utils, Type: Refactor

#53 Feature/order
  package-lock.json
  src/database/repositories/order.repository.ts
  src/database/repositories/ticket.repository.ts
  src/orders/dtos/request-order.dto.ts
  src/orders/orders.controller.ts
  src/orders/orders.module.ts
  src/orders/orders.service.ts
  src/tickets/dtos/create-ticket.dto.ts
Labels: Type: Feature

#54 :hammer: fix(order): 티켓생성 한번에 비동기요청 리펙토링#42
  src/orders/orders.service.ts
Labels: Type: Refactor

#59 🚀 feat: redis / bull.js 이용하여 슬랙 알람 및 네이버 sms 비동기 처리
  package-lock.json
  package.json
  src/database/entities/ticket.entity.ts
  src/database/repositories/ticket.repository.ts
  src/orders/orders.module.ts
  src/orders/orders.service.ts
  src/queue/queue.consumer.sms.ts
  src/queue/queue.consumer.ts
  src/queue/queue.module.ts
  src/queue/queue.service.ts
  src/slack/slack.module.ts
  src/slack/slack.service.ts
  src/sms/sms.service.ts
  src/tickets/tickets.module.ts
  src/tickets/tickets.service.ts
Labels: For: Utils, Type: Feature

#60 ticket enum 타입 마이그레이션 진행
  package-lock.json
  package.json
  src/common/consts/enum.ts
  src/common/pipes/ticket-status-validation.pipe.ts
  src/database/entities/comment.entity.ts
  src/database/entities/order.entity.ts
  src/database/entities/ticket.entity.ts
  src/database/entities/user.entity.ts
  src/database/migrations/1658837628780-TicketStatusAddEnum.ts
  src/database/migrations/1658841312873-TicketUuidToVARCHAR.ts
  src/database/migrations/typeOrm.config.ts
  src/orders/orders.service.ts
  src/slack/slack.service.spec.ts
  src/tickets/tickets.service.ts
Labels: Type: Refactor, For: Models/DB

#61 주문 중간 배포 , 레디스 큐 관련 배포 v0.0.9
  package-lock.json
  package.json
  src/common/consts/enum.ts
  src/common/pipes/orderId-validation.pipe.ts
  src/common/pipes/ticket-status-validation.pipe.ts
  src/database/entities/comment.entity.ts
  src/database/entities/order.entity.ts
  src/database/entities/ticket.entity.ts
  src/database/entities/user.entity.ts
  src/database/migrations/1658837628780-TicketStatusAddEnum.ts
  src/database/migrations/1658841312873-TicketUuidToVARCHAR.ts
  src/database/migrations/typeOrm.config.ts
  src/database/repositories/order.repository.ts
  src/database/repositories/ticket.repository.ts
  src/orders/dtos/request-order.dto.ts
  src/orders/orders.controller.ts
  src/orders/orders.module.ts
  src/orders/orders.service.ts
  src/queue/queue.consumer.sms.ts
  src/queue/queue.consumer.ts
  src/queue/queue.module.ts
  src/queue/queue.service.ts
  src/slack/slack.module.ts
  src/slack/slack.service.spec.ts
  src/slack/slack.service.ts
  src/slack/slackFake.service.ts
  src/sms/sms.service.ts
  src/socket/socket-admin.gateway.ts
  src/socket/socket.service.ts
  src/tickets/dtos/create-ticket.dto.ts
  src/tickets/dtos/update-ticket-status.dto.ts
  src/tickets/tickets.module.ts
  src/tickets/tickets.service.ts
Labels: For: Deploy, Status: WIP, Type: Feature

#63 :hammer: fix(auth) : 서비스레이어에서 디티오 클래스로 반환, 전화번호 검증 로직 보완
  src/auth/auth.service.ts
  src/auth/dtos/AdminSendValidationNumber.request.dto copy.ts
  src/auth/dtos/RegisterUser.response.dto.ts
  src/auth/dtos/phoneNumber.request.dto.ts
  src/queue/queue.service.spec.ts
  src/slack/slack.module.ts
  src/slack/slack.service.spec.ts
  src/slack/slack.service.ts
Labels: For: Utils, Type: Refactor, Type: Docs/Chore

#66 🔨 refactor(queue): 문자 형식 변경 및 순서 보장 로직 추가
  package-lock.json
  src/common/consts/enum.ts
  src/queue/queue.consumer.sms.ts
  src/queue/queue.service.ts
  src/sms/sms.service.ts
Labels: For: Utils, Type: Feature, Type: Refactor

#64 Feature/order 주문생성시 Response 실응답과 swagger예시 맞춤
  package-lock.json
  src/database/repositories/order.repository.ts
  src/orders/dtos/request-order.dto.ts
  src/orders/dtos/response-order.dto.ts
  src/orders/dtos/response-orderlist.dto.ts
  src/orders/orders.controller.ts
  src/orders/orders.service.ts
  src/queue/queue.service.ts
Labels: Status: WIP, Type: Feature, For: API

#74 :hammer: fix(ticket) /ticket/create 유저가 null 인 에러 해결 #73
  src/tickets/tickets.controller.ts
Labels: Type: Errors/Bugs, Status: URGENT

#75 🚀 스웨거 에러 데코레이터 추가
  src/app.controller.ts
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/guards/AccessToken.guard.ts
  src/common/decorators/ErrorResponse.decorator.ts
  src/common/errors/ErrorCommonResponse.dto.ts
  src/common/errors/HttpErrorNameEnum.ts
  src/common/errors/HttpExceptionError.response.dto.ts
  src/common/errors/ValidationError.response.dto.ts
  src/common/errors/ValidtionError.ts
  src/common/exceptions/http-exception.filter.ts
  src/common/utils/enumNumberToArray.ts
  src/common/utils/makeInstanceByApiProperty.ts
Labels: For: Utils, Type: Feature, Type: Docs/Chore

#76 에러 응답 예시, 데코레이터 ,응답 예시 보강 배포
  package-lock.json
  src/app.controller.ts
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/dtos/AdminSendValidationNumber.request.dto copy.ts
  src/auth/dtos/AdminSendValidationNumber.response.dto.ts
  src/auth/dtos/BaseValidateNumber.response.dto.ts
  src/auth/dtos/FirstRegister.response.dto copy.ts
  src/auth/dtos/Login.response.dto.ts
  src/auth/dtos/RegisterUser.response.dto.ts
  src/auth/dtos/phoneNumber.request.dto.ts
  src/auth/guards/AccessToken.guard.ts
  src/common/consts/enum.ts
  src/common/decorators/ErrorResponse.decorator.ts
  src/common/errors/ErrorCommonResponse.dto.ts
  src/common/errors/HttpErrorNameEnum.ts
  src/common/errors/HttpExceptionError.response.dto.ts
  src/common/errors/ValidationError.response.dto.ts
  src/common/errors/ValidtionError.ts
  src/common/exceptions/http-exception.filter.ts
  src/common/utils/enumNumberToArray.ts
  src/common/utils/makeInstanceByApiProperty.ts
  src/database/repositories/order.repository.ts
  src/orders/dtos/request-order.dto.ts
  src/orders/dtos/response-order.dto.ts
  src/orders/dtos/response-orderlist.dto.ts
  src/orders/orders.controller.ts
  src/orders/orders.service.ts
  src/queue/queue.consumer.sms.ts
  src/queue/queue.service.spec.ts
  src/queue/queue.service.ts
  src/slack/slack.module.ts
  src/slack/slack.service.spec.ts
  src/slack/slack.service.ts
  src/sms/sms.service.ts
  src/tickets/tickets.controller.ts
Labels: For: Deploy, Type: Feature, For: API, Type: Docs/Chore

#78 🚀 스웨거 같은 상태코드 여러예시 데코레이터 추가
  src/app.controller.ts
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/guards/AccessToken.guard.ts
  src/auth/guards/RegisterToken.guard.ts
  src/common/decorators/ErrorResponse.decorator.ts
  src/common/decorators/SuccessResponse.decorator.ts
  src/common/decorators/registerUser.decorator.ts
  src/common/decorators/returnValueToDto.decorator.ts
  src/common/decorators/user.decorator.ts
  src/common/dtos/SuccessCommonResponse.dto.ts
  src/common/exceptions/http-exception.filter.ts
  src/common/funcs/toKRTimezone.ts
  src/common/interceptors/sucess.interceptor.ts
  src/common/utils/makeInstanceByApiProperty.ts
  src/common/utils/mergeTwoObj.ts
  src/database/migrations/typeOrm.config.ts
  src/database/repositories/ticket.repository.ts
  src/database/repositories/user.repository.spec.ts
  src/database/repositories/user.repository.ts
  src/queue/queue.consumer.sms.ts
  src/queue/queue.consumer.ts
  src/queue/queue.service.ts
  src/redis/redis.service.ts
  src/slack/slack.service.spec.ts
  src/slack/slack.service.ts
  src/socket/socket.service.ts
  src/tickets/tickets.controller.ts
Labels: For: Utils, Type: Feature, Type: Docs/Chore

#79 🔨 makeInstanceByApiProperty 함수 생성자 대응, 페이지네이션 예시 추가
  src/auth/auth.controller.ts
  src/common/decorators/ErrorResponse.decorator.ts
  src/common/decorators/SuccessResponse.decorator.ts
  src/common/dtos/page/page-meta.dto.ts
  src/common/dtos/page/page.dto.ts
  src/common/utils/makeInstanceByApiProperty.ts
  src/database/entities/comment.entity.ts
  src/database/entities/order.entity.ts
  src/database/entities/ticket.entity.ts
  src/database/entities/user.entity.ts
  src/tickets/tickets.controller.ts
Labels: For: Utils, Type: Refactor, Type: Docs/Chore

#87 [v0.1.1] 주문모듈 통계_관리자 관련 api 배포 ,에러코드화
  package-lock.json
  src/app.controller.ts
  src/app.module.ts
  src/auth/Errors/AuthErrorDefine.ts
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/guards/AccessToken.guard.ts
  src/auth/guards/RegisterToken.guard.ts
  src/auth/guards/TrottlerBehindProxy.guard.ts
  src/common/decorators/ErrorResponse.decorator.ts
  src/common/decorators/SuccessResponse.decorator.ts
  src/common/decorators/registerUser.decorator.ts
  src/common/decorators/returnValueToDto.decorator.ts
  src/common/decorators/user.decorator.ts
  src/common/dtos/SuccessCommonResponse.dto.ts
  src/common/dtos/page/page-meta.dto.ts
  src/common/dtos/page/page.dto.ts
  src/common/errors/HttpExceptionError.response.dto.ts
  src/common/errors/ValidationError.response.dto.ts
  src/common/errors/ValidtionError.ts
  src/common/exceptions/http-exception.filter.ts
  src/common/funcs/toKRTimezone.ts
  src/common/interceptors/sucess.interceptor.ts
  src/common/pipes/orderId-validation.pipe.ts
  src/common/utils/makeInstanceByApiProperty.ts
  src/common/utils/mergeTwoObj.ts
  src/database/entities/comment.entity.ts
  src/database/entities/order.entity.ts
  src/database/entities/ticket.entity.ts
  src/database/entities/user.entity.ts
  src/database/migrations/typeOrm.config.ts
  src/database/repositories/order.repository.ts
  src/database/repositories/ticket.repository.ts
  src/database/repositories/user.repository.spec.ts
  src/database/repositories/user.repository.ts
  src/orders/dtos/enter-report.dto.ts
  src/orders/dtos/order-find.dto.ts
  src/orders/dtos/order-report.dto.ts
  src/orders/dtos/report.dto.ts
  src/orders/dtos/ticket-report.dto.ts
  src/orders/dtos/update-order-status.dto.ts
  src/orders/orders.controller.ts
  src/orders/orders.module.ts
  src/orders/orders.service.ts
  src/queue/queue.consumer.sms.ts
  src/queue/queue.consumer.ts
  src/queue/queue.service.ts
  src/redis/redis.service.ts
  src/slack/slack.service.spec.ts
  src/slack/slack.service.ts
  src/socket/socket.service.ts
  src/tickets/tickets.controller.ts
  src/tickets/tickets.module.ts
Labels: For: Deploy, For: Utils, Type: Feature, For: API, Type: Docs/Chore

#95 :hammer: fix(util) : 어레이형 타입 꺼내오기로 수정
  src/common/utils/makeInstanceByApiProperty.ts
  src/database/entities/order.entity.ts
  src/tickets/tickets.controller.ts
Labels: For: Utils, Type: Errors/Bugs, Status: URGENT

#96 [v0.1.1] 유저모듈, 주문모듈 리팩토링 배포
  package-lock.json
  package.json
  src/auth/auth.module.ts
  src/common/utils/makeInstanceByApiProperty.ts
  src/database/database.module.ts
  src/database/entities/order.entity.ts
  src/database/repositories/comment.repository.ts
  src/database/repositories/user.repository.ts
  src/orders/dtos/report.dto.ts
  src/orders/orders.controller.ts
  src/orders/orders.service.ts
  src/users/dtos/Comment.dto.ts
  src/users/dtos/Comment.request.dto.ts
  src/users/dtos/Comment.response.dto.ts
  src/users/dtos/Scroll/ScrollComment.response.dto.ts
  src/users/dtos/Scroll/ScrollComments.response.dto.ts
  src/users/dtos/Scroll/ScrollMeta.dto.ts
  src/users/dtos/Scroll/ScrollOptions.dto.ts
  src/users/dtos/User.response.dto.ts
  src/users/dtos/UserName.request.dto.ts
  src/users/dtos/UserTicketNum.response.dto.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: For: Deploy, For: Utils, Type: Feature, Type: Refactor, For: API, Type: Errors/Bugs

#98 🔨refactor(user) : 댓글 스크롤 조회 기능 수정 #91
  src/database/repositories/comment.repository.ts
  src/users/dtos/Scroll/ScrollMeta.dto.ts
  src/users/dtos/Scroll/ScrollOptions.dto.ts
  src/users/users.service.spec.ts
Labels: Type: Refactor, For: API

#100 [v0.1.3] n번째 티켓(랜딩페이지용), 댓글 조회기능 수정 배포
  src/auth/guards/AccessToken.guard.ts
  src/auth/guards/NoAuth.guard.ts
  src/database/repositories/comment.repository.ts
  src/database/repositories/ticket.repository.ts
  src/tickets/dtos/ticket-count.dto.ts
  src/tickets/tickets.controller.ts
  src/tickets/tickets.service.ts
  src/users/dtos/Scroll/ScrollMeta.dto.ts
  src/users/dtos/Scroll/ScrollOptions.dto.ts
  src/users/users.service.spec.ts
Labels: For: Deploy, Type: Feature, Type: Refactor, For: API
